- README.md
I've added `Sys.setlocale("LC_CTYPE", "Chinese")` to my .RProfile.site so I can see the spark-histogram characters :)
> add workaround to show characters in windows

- R/functions.R
- R/stats.R
Currently the documentation for n_unique says it returns the number of unique values but it actually returns the vector of unique values, which is then composed with purrr to get the length.  This changes n_unique to include length() and return the number as described.  Also the PR changes the calls to n_unique to be direct rather than composed.
> Make n_unique match its documentation.

- DESCRIPTION
- R/defaults.R
- R/functions.R
- tests/testthat/test-functions.R
Improved documentation of functions for working with the skimming functions. Also,  move default functions to their own file to make it easier to read the code in functions.R.
This PR removes ordered = factor_funs from the list of defaults. The dispatch system should do this for us automatically. This behavior remains untested.
> Fixes #115

- R/functions.R
- man/show_skimmers.Rd
- man/skim_with.Rd
- tests/testthat/test-functions.R
Give users the option of selecting which summary functions are returned by show_skimmers. It does this by accepting an argument for a data type/ class.
For example skim_with("numeric") gives the names of functions used to summarize numeric data.
> Fixes #116 and #121

- CONTRIBUTING.md
- R/functions.R
Two things:
I noticed that "nake_case" should be "snake_case" when reading the contributing file. 
In my other pull request @elinw mentioned that it would be cleaner to assign posixct_funs to date_funs since they are identical (I was not sure if it was better to keep that separate from the other PR or to put it here. Happy to swap it to the other one if that would be preferred).
> typo and posixct simplification

- R/skim.R
R CMD check doesn't currently respect quoting within rlang::quo.
Use base R quote instead.
> Fix note due to global variable

- R/stats.R
- tests/testthat/test-skim_v.R
- tests/testthat/test-stats.R
This should fix #255 :
``` r
library(skimr)
a = data.frame(var = c(0,0,0,NA))
skim(a)
#> Skim summary statistics
#>  n obs: 4 
#>  n variables: 1 
#> 
#> Variable type: numeric 
#>  variable missing complete n mean sd p0 p25 median p75 p100     hist
#>       var       1        3 4    0  0  0   0      0   0    0 <U+2581><U+2581><U+2581><U+2587><U+2581><U+2581><U+2581><U+2581>
```
> add na.rm = TRUE to fix #255

- R/stats.R
To avoid partial name matching, I've changed the `length` argument in `seq()` calls to `length.out`.
After setting: `options(warnPartialMatchArgs = TRUE)`
I get `partial argument match of 'length' to 'length.out'` every time I run `skim()`
some of the other calls to `seq()` in this package have `length.out`.
First time contributing. Sorry if I don't do it correctly.
> update seq( ) parameter to length.out

- R/stats.R
- tests/testthat/test-skim.R
Thanks for the great package!
I encountered a few issues when I was trying to skim a dataframe with infinite values, so I wrote a quick PR. Let me know if I should make any changes!
- Replace `seq(..., length = )` with `seq(..., length.out = )` to exactly match the argument (courtesy of [strict](https://github.com/hadley/strict/))
- Fix issues with histograms of infinite or NA values
- Add tests for those histograms
- Remove a bunch of trailing whitespaces because of Atom
> Allow histogram with infinite values

- R/skim.R
- R/skim_v.R
- man/kable.Rd
- man/skim_format.Rd
- man/skim_with.Rd
- tests/testthat/test-functions.R
- tests/testthat/test-skim_v.R
from the skim results. For a single vector a message indicates that there is not a skimmer for that class.  This is deliberately different handling than for the case where a given class does not exist at all (in which case skim() falls back to character).
> An empty function list for a class should not cause an error and should eliminate that class 

- README.Rmd
- README.md
- vignettes/Skimr_defaults.Rmd
I noticed this on CRAN:
And thought I'd just fix it rather than create an issue.
> Fix vignette title

- R/get_skimmers.R
- man/get_skimmers.Rd
This fixes the failing example (and I think it's a more explanatory example anyway).
> Update example for creating an integer skimmer

- R/get_skimmers.R
- R/sfl.R
- R/skim_with.R
- man/get_skimmers.Rd
- man/sfl.Rd
- man/skim_with.Rd
- tests/testthat/test-sfl.R
- tests/testthat/test-skim_with.R
Closes #369
For more info, see tidyverse/dplyr/issues/3433
> Deal with dplyr deprecation of funs().

- R/skim_print.R
- tests/testthat/test-skim_print.R
Use tibble print instead of erroring if the data type is inappropriate.
> In `knit_print`, enable fallback

- tests/testthat/helper-expectations.R
Now the reference files won't change when calling the test multiple times.
> Switch match expectation to update = FALSE

- R/skim_print.R
- tests/testthat/print/groups.txt
This handles bugs where certain kinds of metadata were appearing.
Closes #464
> Check for spaces when removing metadata

- README.Rmd
- README.md
Awesome project! Just caught a little formatting issue in the README. Thanks.
> Fix typo in formatting inline code in README

- R/skim_print.R
- man/print.Rd
It on by default. But this might be the root cause of some environments not printing.
> Add option for stripping tibble metadata.

- DESCRIPTION
- R/skim_print.R
- codemeta.json
- tests/testthat/test-skim_print.R
On a number of platforms in version 2 the bodies of the skimr tables that display when printing are empty.  We have been advising people to manually set options(crayon.enabled = FALSE).  This is both awkward and can have side effects.   This PR follows the model here
https://github.com/r-lib/crayon/issues/83#issuecomment-473428346
> Crayon tibble issue where table bodies are blank

- R/skim_with.R
On lazy-loaded, is.data.frame is slower and more expensive, often causing big copies. As it turns out, all is.data.frame does is call inherits(x, "data.frame").  inherits is a internal function, making it much more efficient (and less likely to create unnecessary copies).
> Use inherits() instead of is.data.frame()

- DESCRIPTION
- appveyor.yml
- tests/testthat/print/knit_print-summary.txt
- tests/testthat/print/knit_print.txt
Two tests in this package need to be updated accordingly.
This is because you provided the caption to `knitr::kable()`: https://github.com/ropensci/skimr/blob/b8be86090de8c5daf52f062f260aa5694880c994/R/skim_print.R#L166
In previous versions of **knitr**, the caption was silently ignored, which was not a good idea. Since **knitr** 1.29, it has changed (https://github.com/yihui/knitr/pull/1830). It will be great if you could update your tests accordingly. Thank you very much!
> Since knitr v1.29, knitr::kable() will add the table caption if provided

- DESCRIPTION
- R/skim.R
- R/skim_with.R
- man/skim.Rd
- tests/testthat/test-skim.R
I gave fixing #611 a try. As predicates were introduced in tidyselect 1.0 this changes the required tidyselect version.
> Adds support for predicates (Issue #611)

- R/skim_with.R
- tests/testthat/test-get_skimmers.R
- tests/testthat/test-reshape.R
- tests/testthat/test-sfl.R
- tests/testthat/test-skim.R
- tests/testthat/test-skim_print.R
Fixes #615.
Also resolves deprecation of expect_is() in testthat.
> Set ignore.case = FALSE in `tidyselect::starts_withs()`

- DESCRIPTION
- NEWS.md
- R/skim_with.R
This PR supersedes #674 to cleanly rebase and add better benchmarking. 
This very small PR replaces `as.data.frame` with `as_tibble` inside the `reshape_skimmed` function. This has a significant impact on performance, particularly for large datasets: `as.data.frame` is known to be slow (see [here](https://adv-r.hadley.nz/perf-improve.html#as.data.frame)) and in combination with increased calls to `reshape_skimmed` as variables are added leads to an exponential degradation in performance with dataset size.
<details>
<summary>code</summary>
```R
library(tidyverse)
library(stringi)
library(skimr)
library(microbenchmark)
#devtools::install_github("ropensci/skimr@develop")
rows <- c(100,1000,10000)
cols <- c(30,90,300,600,900,1200)
results <- list()
for(r in 1:length(rows)){
results[[r]] <- …
```
> Replace as.data.frame to improve performance

- R/skim_print.R
Fixes #700 
`downlit::evaluate_and_highlight()` requires that we return something invisibly. It has no other user-facing effects.
> Fix pkgdown failure

- R/reshape.R
- R/skim_with.R
- tests/testthat/test-skim_with.R
The root cause of the problem is that `list_modify(x, y = NULL)` now returns list(y = NULL)` rather than removing `y` as previously. So I made two changes:
* `merge_skimmers()` removes the NULL skimmers after merging
* I don't know why `get_local_skimmers()`  broke but once I figured out what it was doing, I rewrote it from first principles and it now works.
(Also includes some remaining tidyselect tweaks to avoid warnings in the tests)
> Fixes for dev purrr

- R/skim.R
`?skimr::skim` says
>  Please review the _Using Skimr_ vignette for more information (‘vignette("Using_skimr", package = "skimr")’
```
Vignettes in package ‘skimr’:
extending_skimr         Extending skimr (source, html)
Skimr_defaults          Skimr defaults (source, html)
Using_fonts             Using Fonts (source, html)
skimr                   Using Skimr (source, html)
```
Update `vignette("Using_skimr", package = "skimr")’ --> `vignette("Using_skimr", package = "skimr")’
change name of `vignettes/skimr.Rmd` to  `Using_vignettes/skimr.Rmd`
> Fix typo in vignette() call
