ropensci/skimr

DESCRIPTION
tests/testthat.R
tests/testthat/test-skim.R

We're going to want some sort test to make sure this works. This gets us started.

Add test skeletons, with the possibility of changing default statistics.

---

tests/testthat/test-skim_v.R

fixed numeric test

---

R/stats.R

All zero variables causing error, this PR checks for that and returns a 0 value instead of a histogram for those variables.

Resolved ropensci/skimr#45

---

README.md

document Windows printing issue

---

DESCRIPTION
R/stats.R
README.md
blog.Rmd
blog.md

Update colformat dependency to new name pillar; fixes #137

---

R/skim.R
tests/testthat/test-skim_print.R

The rest of the fixes needed for test-skim_print.

Print engine tests

---

R/skim.R
R/skim_print.R

Suppress dplyr::do progress bars.

---

CONTRIBUTING.md
inst/markdown/templates/fonts_in_skimr/skeleton/skeleton.Rmd

A few typos fixed

---

R/stats.R
README.Rmd
README.md
man/skim.Rd
man/skim_format.Rd
man/stats.Rd
tests/testthat/test-stats.R

This does some updates based on several different issues currently in the tracker some of which are also in the onboarding comments.

Update some tests and README

---

NEWS.md
tests/testthat/test-skim_print.R

Or ones that got written over ..

Some missed commits 

---

NEWS.md
R/skim.R
R/skim_print.R
man/skim.Rd
tests/testthat/test-skim_print.R

Missing comma

---

R/reshape.R
R/skim.R
man/partition.Rd
man/sfl.Rd
man/skim.Rd
man/stats.Rd

Add details on new reshaping API. Remove references to old reshaping API.

Update skim.R docs

---

DESCRIPTION

Adding myself as a contributor, as requested in #338.

Add contributor

---

vignettes/Using_skimr.Rmd

Fix typo, thanks @AndreaPi

---

DESCRIPTION
R/skim_with.R
man/reexports.Rd
tests/testthat/test-skim.R

This allows us to handle vectors as we do in v1.  It will also handle matrices, which is a request we got although we turned it down.

Coerce non data frames to data frames.

---

R/skim_print.R
tests/testthat/test-skim_print.R

This will help increase v2 test coverage. (#103)

Add tests for knit_print.summary_skim_df

---

R/skim_obj.R
man/skim-obj.Rd
tests/testthat/test-dplyr.R
tests/testthat/test-reshape.R

Closes #393 
Add some more tests too.

 skim dfs should have more than 0 rows.  

---

NEWS.md
R/stats.R
tests/testthat/test-stats.R

They should return NA for max() and min() instead of -Inf and Inf.

V2 fix for all character vectors 

---

R/skim_print.R
tests/testthat/dplyr/arrange.txt
tests/testthat/dplyr/filter-skim.txt
tests/testthat/dplyr/mutate-skim.txt
tests/testthat/dplyr/select-skim.txt
tests/testthat/dplyr/slice.txt
tests/testthat/print/default.txt
tests/testthat/print/focus.txt
tests/testthat/print/groups.txt
tests/testthat/print/knit_print-summary.txt
tests/testthat/print/knit_print.txt
tests/testthat/print/list.txt
tests/testthat/print/no-hist.txt
tests/testthat/print/smaller.txt

V2 spaces between subtables

---

vignettes/skimr.Rmd

This will give us another automatic tab in the pkgdown site.
Closes #441

Rename getting started vignette

---

README.Rmd
README.md

Fix name: v-2 -> v2

---

.gitattributes

See https://github.com/ropensci/dev_guide/issues/171 for more info.

Exclude blog post from repo stats

---

R/skim_print.R
R/summary.R
tests/testthat/dplyr/arrange.txt
tests/testthat/dplyr/filter-skim.txt
tests/testthat/dplyr/mutate-skim.txt
tests/testthat/dplyr/select-skim.txt
tests/testthat/dplyr/slice.txt
tests/testthat/print/default.txt
tests/testthat/print/focus.txt
tests/testthat/print/groups.txt
tests/testthat/print/knit_print-summary.txt
tests/testthat/print/knit_print.txt
tests/testthat/print/no-hist.txt
tests/testthat/print/repr.txt
tests/testthat/print/smaller.txt

This fixes problems in the formatting of summary when knitting. 
The approach replaces the prior concatenation of a string with use of a table object (like that produced by the base `table()` function).

Markdown to pdf

---

DESCRIPTION
R/skim_with.R

 Update unnest syntax for tidyr 1.0

---

.Rbuildignore
.gitignore
.pre-commit-config.yaml
CONTRIBUTING.md
NEWS.md
R/dplyr.R
R/reshape.R
R/skim_print.R
R/skim_with.R
R/stats.R
R/summary.R
README.Rmd
README.md
man/knit_print.Rd
man/mutate.skim_df.Rd
man/partition.Rd
man/stats.Rd
man/summary.skim_df.Rd
tests/testthat/helper-expectations.R
tests/testthat/test-skim_print.R
tests/testthat/test-skim_with.R
tests/testthat/test-stats.R
tests/testthat/test-summary.R
vignettes/Supporting_additional_objects.Rmd
vignettes/skimr.Rmd

This corrects a few different code health issues after running pre-commit checks.

Pre commits

---

README.Rmd
README.md

Hold off on this until #487 is merged.

Cran checks v2

---

R/skim.R
man/skim.Rd

Let me now if you find any others that I can add!

Remove reference to long data frame in skim() docs

---

R/skim_with.R
man/skim_with.Rd

* Make the documentation at the top clearer.
* Fix the arguments for build_results and skim_by_type.

Clean up `skim_with()`.

---

R/skim_print.R
R/skimr-package.R
man/print.Rd
tests/testthat/print/strip-opt.txt
tests/testthat/print/strip.txt
tests/testthat/test-skim_print.R

Add an option for controlling tibble metadata

---

R/skim_print.R
man/print.Rd

Add a link in print docs to tibble's options

---

DESCRIPTION

Very small. I seem to have mistyped my name in the description file...sorry. Please let me know if you'd like me to do this differently since it's so small.

Update name in DESCRIPTION

---

DESCRIPTION

closes  #588
As discussed in #588, I added myself as a ctb.

added David as ctb

---

R/skim_with.R

Suffixed functions are superceded:
https://dplyr.tidyverse.org/articles/colwise.html#-if-at-all

Switch to dplyr::across

---

R/dplyr.R
R/sfl.R
man/mutate.skim_df.Rd
man/sfl.Rd
man/skimr-vctrs.Rd

Clean up docs

---

README.Rmd

Add inspirations

---

README.Rmd
README.md

I got this to build as is on a windows machine using WSL. Opening this PR to fix

Revert changes to README

---

NEWS.md
R/skim_print.R
man/mutate.skim_df.Rd
man/print.Rd
tests/testthat/helper-expectations.R
tests/testthat/print/narrow-header.txt
tests/testthat/test-skim_print.R

Add an option for subtable header width

---

R/skim_print.R
man/print.Rd

Found when rebuilding documentation.

Missing : in document

---

DESCRIPTION

Move crayon and withr to suggests

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
R/reshape.R
R/skim_print.R
R/skim_with.R
man/deprecated-v1.Rd
man/get_default_skimmers.Rd
man/get_skimmers.Rd
man/knit_print.Rd
man/partition.Rd
man/print.Rd
man/skim-attr.Rd
man/skim-obj.Rd
man/stats.Rd
man/to_long.Rd

We're now being a little stricter with inputs.

Fixes for dev tidyselect

---

DESCRIPTION
NEWS.md
README.Rmd
README.md
codemeta.json
man/deprecated-v1.Rd
man/get_default_skimmers.Rd
man/get_skimmers.Rd
man/knit_print.Rd
man/partition.Rd
man/print.Rd
man/skim-attr.Rd
man/skim-obj.Rd
man/stats.Rd
man/to_long.Rd

Prepare for release

---

DESCRIPTION
R/skim_print.R
man/knit_print.Rd
man/skimr-package.Rd

Thanks for the offer @michaelquinn32 ! https://github.com/ropensci/skimr/issues/751#issuecomment-2613559260
I also fixed a R CMD CHECK NOTE by removing a link to `collapse()`. I couldn't find where this function is coming from.

Links + add Olivier as contributor
